version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    depends_on: 
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres@db
      RAILS_ENV: production
      SECRET_KEY_BASE: verysecret
  
  db:
    image: postgres:9.5
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  
  redis:
    image: redis
    ports:
      - 6379:6379


volumes:
  dbdata:
